// Consistent display names for the people discussed in the book.
#let names = (
  "Albert": "Алберт (Albert A. A.)",
  "Алберт": "Алберт (Albert A. A.)",
  "Amitsur": "Амицур (Amitsur S. A.)",
  "Амицур": "Амицур (Amitsur S. A.)",
  "Artin": "Артин (Artin E.)",
  "Артин": "Артин (Artin E.)",
  "Auslander": "Ауслендер (Auslander M.)",
  "Ауслендер": "Ауслендер (Auslander M.)",
  "Belluce": "Беллюс (Belluce L. P.)",
  "Беллюс": "Беллюс (Belluce L. P.)",
  "Bergman": "Бергман (Bergman G.)",
  "Бергман": "Бергман (Bergman G.)",
  "Burnside": "Бернсайд (Burnside W.)",
  "Бернсайд": "Бернсайд (Burnside W.)",
  "Brauer": "Брауэр (Brauer R.)",
  "Брауэр": "Брауэр (Brauer R.)",
  "Wedderburn": "Веддербарн (Wedderburn J. H. M.)",
  "Веддербарн": "Веддербарн (Wedderburn J. H. M.)",
  "Wielandt": "Виланд (Wielandt H.)",
  "Виланд": "Виланд (Wielandt H.)",
  "Villamayor": "Вильямайер (Villamayor O.)",
  "Вильямайер": "Вильямайер (Villamayor O.)",
  "Goldie": "Голди (Goldie A. W.)",
  "Голди": "Голди (Goldie A. W.)",
  "Goldman": "Голдмен (Goldman O.)",
  "Голдмен": "Голдмен (Goldman O.)",
  "Golod": "Голод Е. С.",
  "Голод": "Голод Е. С.",
  "Hopkins": "Гопкинс (Hopkins C.)",
  "Гопкинс": "Гопкинс (Hopkins C.)",
  "Hurwitz": "Гурвиц (Hurwitz A.)",
  "Гурвиц": "Гурвиц (Hurwitz A.)",
  "Deuring": "Дейринг (Deuring M.)",
  "Дейринг": "Дейринг (Deuring M.)",
  "Jain": "Джайн (Jain S. K.)",
  "Джайн": "Джайн (Jain S. K.)",
  "Jacobson": "Джекобсон (Jacobson N.)",
  "Джекобсон": "Джекобсон (Jacobson N.)",
  "Dickson": "Диксон (Dickson L. E.)",
  "Диксон": "Диксон (Dickson L. E.)",
  "Zelinsky": "Зелинский (Zelinsky D.)",
  "Зелинский": "Зелинский (Zelinsky D.)",
  "Ikeda": "Икеда (Ikeda M.)",
  "Икеда": "Икеда (Ikeda M.)",
  "Kaplansky": "Капланский (Kaplansky I.)",
  "Капланский": "Капланский (Kaplansky I.)",
  "Kothe": "Кёте (Köthe G.)",
  "Кёте": "Кёте (Köthe G.)",
  "Kurosh": "Курош А. Г.",
  "Курош": "Курош А. Г.",
  "Curtis": "Кэртис (Curtis C.)",
  "Кэртис": "Кэртис (Curtis C.)",
  "Levitzki": "Левицкий (Levitzki J.)",
  "Левицкий": "Левицкий (Levitzki J.)",
  "McLaughlin": "Маклафлин (McLaughlin J.)",
  "Маклафлин": "Маклафлин (McLaughlin J.)",
  "Martindale": "Мартиндейл (Martindale W.)",
  "Мартиндейл": "Мартиндейл (Martindale W.)",
  "Maschke": "Машке (Maschke H.)",
  "Машке": "Машке (Maschke H.)",
  "Nagata": "Нагата (Nagata M.)",
  "Нагата": "Нагата (Nagata M.)",
  "Nakayama": "Накаяма (Nakayama T.)",
  "Накаяма": "Накаяма (Nakayama T.)",
  "Nesbitt": "Несбитт (Nesbitt C.)",
  "Несбитт": "Несбитт (Nesbitt C.)",
  "Noether": "Нётер (Noether E.)",
  "Нётер": "Нётер (Noether E.)",
  "Novikov": "Новиков П. С.",
  "Новиков": "Новиков П. С.",
  "Ore": "Оре (Ore O.)",
  "Оре": "Оре (Ore O.)",
  "Passman": "Пассман (Passman D. S.)",
  "Пассман": "Пассман (Passman D. S.)",
  "Posner": "Познер (Posner E.)",
  "Познер": "Познер (Posner E.)",
  "Procesi": "Прочези (Procesi C.)",
  "Прочези": "Прочези (Procesi C.)",
  "Reiner": "Райнер (Reiner I.)",
  "Райнер": "Райнер (Reiner I.)",
  "Rickart": "Риккарт (Rickart C. E.)",
  "Риккарт": "Риккарт (Rickart C. E.)",
  "Rosenberg": "Розенберг (Rosenberg A.)",
  "Розенберг": "Розенберг (Rosenberg A.)",
  "Sasiada": "Сансяда (Sasiada E.)",
  "Сансяда": "Сансяда (Sasiada E.)",
  "Serre": "Серр (Serre J.-P.)",
  "Серр": "Серр (Serre J.-P.)",
  "Skolem": "Сколем (Skolem T.)",
  "Сколем": "Сколем (Skolem T.)",
  "Small": "Смолл (Small L.)",
  "Смолл": "Смолл (Small L.)",
  "Thompson": "Томпсон (Thompson J.)",
  "Томпсон": "Томпсон (Thompson J.)",
  "Thrall": "Тролл (Thrall R.)",
  "Тролл": "Тролл (Thrall R.)",
  "Tuzuku": "Тузуку (Tuzuku T.)",
  "Тузуку": "Тузуку (Tuzuku T.)",
  "Utumi": "Утуми (Utumi Y.)",
  "Утуми": "Утуми (Utumi Y.)",
  "Faith": "Фейт (Faith C. C.)",
  "Фейт": "Фейт (Faith C. C.)",
  "Harris": "Харрис (Harris B.)",
  "Харрис": "Харрис (Harris B.)",
  "Harrison": "Харрисон (Harrison D.)",
  "Харрисон": "Харрисон (Harrison D.)",
  "Hasse": "Хассе (Hasse H.)",
  "Хассе": "Хассе (Hasse H.)",
  "Herstein": "Херстейн (Herstein I. N.)",
  "Херстейн": "Херстейн (Herstein I. N.)",
  "Hall": "Холл (Hall M.)",
  "Холл": "Холл (Hall M.)",
  "Chase": "Чейз (Chase S.)",
  "Чейз": "Чейз (Chase S.)",
  "Shafarevitch": "Шафаревич И. Р.",
  "Шафаревич": "Шафаревич И. Р.",
  "Chevalley": "Шевалле (Chevalley C.)",
  "Шевалле": "Шевалле (Chevalley C.)",
  "Schur": "Шур (Schur I.)",
  "Шур": "Шур (Schur I.)",
  "Eckmann": "Экман (Eckmann B.)",
  "Экман": "Экман (Eckmann B.)",
  "Adian": "Адян С. И.",
  "Адян": "Адян С. И.",
  "Kostrikin": "Кострикин А. И.",
  "Кострикин": "Кострикин А. И.",
  "Shirshov": "Ширшов А. И.",
  "Ширшов": "Ширшов А. И.",
  "Cohn": "Кон (Cohn P. M.)",
  "Кон": "Кон (Cohn P. M.)",
  "Lam": "Лэм (Lam T. Y.)",
  "Лэм": "Лэм (Lam T. Y.)",
  "Lang": "Ленг (Lang S.)",
  "Ленг": "Ленг (Lang S.)",
  "Maltsev": "Мальцев А. И.",
  "Мальцев": "Мальцев А. И.",
  "Birkhoff": "Биркгоф (Birkhoff G.)",
  "Биркгоф": "Биркгоф (Birkhoff G.)",
  "Mac Lane": "Маклейн (Mac Lane S.)",
  "Маклейн": "Маклейн (Mac Lane S.)",
  "Van-der-Waerden": "Ван-дер-Варден (van der Waerden B. L.)",
  "Ван-дер-Варден": "Ван-дер-Варден (van der Waerden B. L.)",
  "Köthe": "Кёте (Köthe G.)",
  "Passmann": "Пассман (Passman D. S.)",
)

#let index-name(name) = {
  let name = name.trim()
  let family = if name.ends-with("Mac Lane") { "Mac Lane" } else {
    name.split(",").first().trim().split(" ").last()
  }
  names.at(family, default: name)
}
